services:
  trek:
    build:
      context: ./Trek
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  big-brother:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - trek
    volumes:
      - ./BigBrotherConfig/:/app/BigBrotherConfig/
